import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Welcome</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <nav className={styles.nav}>
          <ul className={styles.list_section}>
            <li><Link href="/#">ABOUT</Link></li>
            <li><Link href="/#">EXPERIENCE</Link></li>
            <li><Link href="/#">EDUCATION</Link></li>
            <li><Link href="/#">PUBLICATIONS</Link></li>
            <li><Link href="/#">CONTACT</Link></li>
            {1 == 2 ? 2 == 3 ? console.log('1') : console.log('2') : console.log('3')}
          </ul>
        </nav>
      <main className={styles.whole}>
        <section className={styles.main}>
          <div className={styles.names}>
              <p className={styles.main_text}>WELCOME</p>
              <p className={styles.main_text}>WELCOME TESTTT</p>
              <p className={styles.main_text}>WELCOME TESTTINGG</p>
            <p className={styles.intro}>Hi. I'm Ayush Nanda. I'm a 4th Year CSE undergraduate at SSN College of Engineering in Chennai.</p>
          </div>
        </section>
      </main>

      </div>


      <footer className={styles.footer}>
        <p>hello</p>
      </footer>
    </>
  )
}
// {/* <div className={styles.boxcontainer}> */}
//   {/* <Image src='/../public/Pic.jpg' height='323px' width='255px' className={styles.profile}/> */}
// {/* </div> */}


